name: Continuous Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Connect to VPS and run command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_NAME}}
          username: ${{ secrets.SERVER_USER}}
          key: ${{ secrets.SSH_KEY}}
          port: 22
          script: |
            cd ~/resource/nextjs-typescript
            git pull origin develop
            npm i
            pm2 delete 0
            npm run build
            pm2 start "npm start"
            service nginx reload
            echo "Success Automation Deploy"
